name: Build and Zip Artifacts

on:
    push:
        branches:
            - "master" # This will match all branches
    pull_request: # Optional: Run on pull requests too

jobs:
    build:
        runs-on: ubuntu-latest # Use Ubuntu for the build environment

        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up pnpm
            - name: Set up pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            # Step 3: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            # Step 4: Install dependencies
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # Step 5: Build the project
            - name: Build the project
              run: pnpm run build

            # Step 6: Get Project Name
            - name: Get Project Name
              id: get-project-name
              run: |
                  PROJECT_NAME=$(node -p "require('./package.json').name")
                  echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT

            # Step 7: Zip the build directory
            - name: Zip the build directory
              run: |
                  cd dist && zip -r ../${{ steps.get-project-name.outputs.PROJECT_NAME }}.zip .
              shell: bash

            # Step 8: Upload the zip file as an artifact
            - name: Upload the artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.get-project-name.outputs.PROJECT_NAME }}
                  path: ${{ steps.get-project-name.outputs.PROJECT_NAME }}.zip
                  compression-level: 0 # Skip compression since file is already zipped
                  retention-days: 5 # Keep the artifact for 5 days
