name: build for osu-counters

on:
    pull_request:
        branches:
            - "CI" # Only run on PRs targeting the CI branch
        types: [opened, synchronize] # Run when PR is opened or updated

jobs:
    build:
        runs-on: ubuntu-latest # Use Ubuntu for the build environment

        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # Adjust to your project's Node.js version

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Build the project
            - name: Build the project
              run: npm run build:ci

            # Step 5: Checkout target repository
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                  repository: ${{ github.actor }}/counters # Checkout the user's fork
                  token: ${{ secrets.TARGET_REPO_PAT }} # PAT secret for authentication
                  path: deploy_target # Checkout to a temporary directory

            # Step 6: Copy build files to target repository
            - name: Copy build files
              run: |
                  TARGET_DIR="deploy_target/counters/customhiterrorbar by breadles5"
                  mkdir -p "$TARGET_DIR" # Ensure the target folder exists
                  echo "Cleaning target directory..."
                  rm -rf "$TARGET_DIR"/* # Remove existing files
                  echo "Copying build files..."
                  cp -r ./dist/* "$TARGET_DIR"/ # Copy build output
              shell: bash

            # Step 7: Commit and push changes to a new branch in target repository
            - name: Commit and push changes to new branch
              id: commit_push
              run: |
                  cd deploy_target
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add "counters/customhiterrorbar by breadles5"/* # Add files from the correct directory
                  # Check if there are changes to commit to avoid empty commits
                  if git diff --staged --quiet --exit-code; then
                    echo "No changes detected in counters directory."
                    echo "changes_exist=false" >> $GITHUB_OUTPUT
                  else
                    BRANCH_NAME="master"
                    echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
                    echo "changes_exist=true" >> $GITHUB_OUTPUT
                    git checkout -b $BRANCH_NAME
                    git commit -m "Update counters from build job ${{ github.run_id }} (${{ github.sha }})"
                    git push --force --set-upstream origin $BRANCH_NAME # Force push to overwrite existing branch if needed
                  fi
              shell: bash

            # Step 8: Create Pull Request using GitHub CLI
            - name: Create Pull Request using GitHub CLI
              if: steps.commit_push.outputs.changes_exist == 'true' # Only run if changes were pushed
              env:
                  GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }} # Use the PAT for authentication
                  GH_REPO: tosuapp/counters # Target repository
                  HEAD_BRANCH: ${{ github.actor }}:${{ steps.commit_push.outputs.branch }} # Correct head branch format
                  BASE_BRANCH: main # Or the default branch of tOSUapp/counters
                  PR_TITLE: "new: custom hit error bar" # Set fixed PR title
                  # --- Set fixed PR body with image URLs ---
                  PR_BODY: |
                    ![customhiterrorbar.png](https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/assets/customhiterrorbar.png)
                    ![customhiterrorbar.gif](https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/assets/customhiterrorbar.gif)

                    tosu
              run: |
                  gh pr create \
                    --repo "$GH_REPO" \
                    --base "$BASE_BRANCH" \
                    --head "$HEAD_BRANCH" \
                    --title "$PR_TITLE" \
                    --body "$PR_BODY"
              shell: bash
